Mastodon/Controllers/Promo/CreatePromoController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using OsOEasy.Data;
using OsOEasy.Data.Models;
using OsOEasy.Services.Stripe;
using OsOEasy.Shared;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace OsOEasy.Controllers.Promo
{
    [Area("Promotion")]
    public class CreatePromoController : Controller
    {

        private readonly ApplicationDbContext _dbContext;
        private readonly ICommon _common;
        private readonly IHostingEnvironment _environment;

        public CreatePromoController(ApplicationDbContext dbContext, ICommon common, IHostingEnvironment environment)
        {
            _dbContext = dbContext;
            _common = common;
            _environment = environment;
        }

        public async Task<IActionResult> CreateNewPromo(string promoId, string promoType)
        {
            var user = await _common.GetCurrentUserAsync(HttpContext);
            if (user == null)
            {
                return RedirectToAction("Login", "Account", new { area = "" });
            }

            HttpContext.Session.SetString("promoId", (string.IsNullOrEmpty(promoId) ? "" : promoId));
            ViewBag.subscription = user.SubscriptionPlan;
            ViewBag.newPromo = (string.IsNullOrEmpty(promoId));
            ViewBag.promoType = promoType;

            return View();
        }

        [HttpGet]
        public JsonResult GetPromoData()
        {
            Promotion promoModel = GetPromoModel(HttpContext.Session.GetString("promoId"));
            return Json(promoModel);
        }

        public Promotion GetPromoModel(string promoId)
        {
            var promo = new Promotion();

            if (!string.IsNullOrEmpty(promoId))
            {
                //Edit existing promotion
                promo = (from x in _dbContext.Promotion where x.Id == promoId select x).FirstOrDefault();
            }
            else
            {
                //Set new promo defaults
                promo.ImageType = "coupon";
                promo.ImageName = "osoeasypromo_coupon (16).svg";
                promo.BackgroundColor = "#ffffff";
                promo.ButtonColor = "#4CAF50";
                promo.SideOfScreen = "right";
                promo.DisplayEndDate = DateTime.Today.AddDays(14).ToString("MM-dd-yyyy");
            }

            return promo;
        }

        [HttpGet]
        public JsonResult GetPromoImages(string imageType)
        {
            IFileProvider provider = new PhysicalFileProvider(Directory.GetCurrentDirectory());
            IDirectoryContents contents = provider.GetDirectoryContents("wwwroot/images/Promo/" + imageType);

            List<string> imageItems = new List<string>();
            foreach (IFileInfo item in contents)
            {
                imageItems.Add(item.Name);
            }

            return Json(imageItems);
        }

        [HttpGet]
        public async Task<JsonResult> GetUserImages()
        {
            var user = await _common.GetCurrentUserAsync(HttpContext);

            IFileProvider provider = new PhysicalFileProvider(Directory.GetCurrentDirectory());
            IDirectoryContents contents = provider.GetDirectoryContents("wwwroot/images/Promo/Users/" + user.Id);

            List<string> imageItems = new List<string>();
            foreach (IFileInfo item in contents)
            {
                imageItems.Add(user.Id + "/" + item.Name);
            }

            return Json(imageItems);
        }

        [HttpGet]
        public JsonResult GetSocialImages(string socialImageType)
        {
            IFileProvider provider = new PhysicalFileProvider(Directory.GetCurrentDirectory());
            IDirectoryContents contents = provider.GetDirectoryContents("wwwroot/images/Social/" + socialImageType);

            List<string> imageItems = new List<string>();
            foreach (IFileInfo item in contents)
            {
                imageItems.Add(item.Name);
            }

            return Json(imageItems);
        }

        [HttpGet]
        public JsonResult GetSocialData()
        {
            SocialSharing socialModel = GetSocialModel(HttpContext.Session.GetString("promoId"));
            return Json(socialModel);
        }

        public SocialSharing GetSocialModel(string promoId)
        {
            var social = new SocialSharing();

            if (!String.IsNullOrEmpty(promoId))
            {
                //Edit existing promotion
                social = (from x in _dbContext.SocialSharing where x.Id == promoId select x).FirstOrDefault();
            }
            else
            {
                social.SideOfScreen = "left";
            }

            return social;
        }

        //todo [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> SaveNewPromo([FromBody]Promotion promoItem)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (_dbContext)
                    {
                        promoItem.CreationDate = DateTime.Now;
                        if (!string.IsNullOrEmpty(promoItem.Id))
                        {
                            //Update existing promotion
                            _dbContext.Entry(_dbContext.Promotion.Find(promoItem.Id)).CurrentValues.SetValues(promoItem);
                        }
                        else
                        {
                            //Create new promotion
                            ApplicationUser appUser = await _common.GetCurrentUserAsync(HttpContext);
                            promoItem.ApplicationUser = appUser;
                            _dbContext.Promotion.Add(promoItem);
                        }

                        _dbContext.SaveChanges();
                    }
                }
                else
                {
                    //todo log that user is trying to bypass UI JS validation
                }
            }
            catch (Exception ex)
            {
                //todo handle exception
            }

            return RedirectToAction("Dashboard", "Dashboard", new { area = "Dashboard" });
        }

        [HttpPost]
        public async Task<IActionResult> SaveSocial([FromBody]SocialSharing socialModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (_dbContext)
                    {
                        if (!string.IsNullOrEmpty(socialModel.Id))
                        {
                            //Update existing promotion
                            _dbContext.Entry(_dbContext.SocialSharing.Find(socialModel.Id)).CurrentValues.SetValues(socialModel);
                        }
                        else
                        {
                            //Create new promotion
                            ApplicationUser appUser = await _common.GetCurrentUserAsync(HttpContext);
                            socialModel.ApplicationUser = appUser;
                            _dbContext.SocialSharing.Add(socialModel);
                        }

                        _dbContext.SaveChanges();
                    }
                }
                else
                {
                    //todo log that user is trying to bypass UI JS validation
                }
            }
            catch (Exception ex)
            {
                //todo handle exception
            }

            return RedirectToAction("Dashboard", "Dashboard", new { area = "Dashboard" });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadUserImage(List<IFormFile> files)
        {

            ApplicationUser appUser = await _common.GetCurrentUserAsync(HttpContext);
            ViewBag.subscription = appUser.SubscriptionPlan;
            //ViewBag.newPromo = (string.IsNullOrEmpty(promoId));
            ViewBag.promoType = "coupon";

            //Image upload only available for paid users
            if (appUser.SubscriptionPlan != SubscriptionOptions.FreeAccount)
            {
                foreach (var formFile in files)
                {
                    if (formFile.Length > 0)
                    {
                        if (FileTypeValid(formFile.FileName))
                        {
                            var fileName = BuildUserPicFileName(formFile.FileName, appUser.Id);
                            using (var stream = new FileStream(fileName, FileMode.Create))
                            {
                                await formFile.CopyToAsync(stream);
                            }
                        }
                        else
                        {
                            //todo handle invalid file types...here and in JS??
                        }
                    }
                }
            }

            return View("CreateNewPromo");
        }

        private string BuildUserPicFileName(string fileName, string userId)
        {
            var userFileDirectory = _environment.WebRootPath + "/images/Promo/Users/" + userId + "/";
            Directory.CreateDirectory(userFileDirectory);

            var myUniqueFileName = Convert.ToString(Guid.NewGuid());
            var FileExtension = Path.GetExtension(fileName);
            var fullFileName = myUniqueFileName + FileExtension;

            return userFileDirectory + fullFileName;
        }

        bool FileTypeValid(string fileName)
        {
            string ext = Path.GetExtension(fileName);
            switch (ext.ToLower())
            {
                case ".jpg":
                    return true;
                case ".jpeg":
                    return true;
                case ".png":
                    return true;
                case ".svg":

Mastodon/Views/Shared/_Layout.cshtml
@inject SignInManager<OsOEasy.Data.Models.ApplicationUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="theme-color" content="#005eff" />
    <meta name="Description" content="@ViewData["MetaDescription"]" />

    <title>@ViewData["Title"]</title>
    <link rel="icon" type="image/x-icon" href="~/favicon.ico">

    <!--jQuery-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous" asp-append-version="true"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"></script>

    <!--HTTP library for AJAX Request (https://github.com/mzabriskie/axios)-->
    <script async src="https://unpkg.com/axios@0.16.2/dist/axios.min.js" asp-append-version="true"></script>

    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />

    <!--Global site CSS-->
    <link async rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />

    <!--Google Fonts-->
    <!--https://fonts.google.com/-->
    <link async href="https://fonts.googleapis.com/css?family=Indie+Flower|Barlow+Semi+Condensed" rel="stylesheet">

    <!--Font Awesome CSS-->
    <link async rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg fixed-top box-shadow header-shadow" style="background-color:#fff">
        <div class="container">

            <button style="color:black" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars" aria-hidden="true"></i>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li>
                        <a style="position:absolute; left:25px" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/osoeasypromo_panda_48.svg" alt="Oso Easy Promo logo, a panda bear" /></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="home" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="features" asp-area="" asp-controller="Home" asp-action="Features">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="pricing" asp-area="" asp-controller="Home" asp-action="Pricing">Pricing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="contact" asp-area="" asp-controller="Home" asp-action="Contact">Contact Us</a>
                    </li>
                    @*<li class="nav-item">
                        <a class="nav-link" id="blog" asp-area="" asp-controller="Home" asp-action="Blog">Blog</a>
                    </li>*@

                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <a class="nav-link" id="dashboard" asp-area="Dashboard" asp-controller="Dashboard" asp-action="Dashboard"><i class="fa fa-gears fa-lg" style="color:red" aria-hidden="true"></i> Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="createPromo" asp-area="Promotion" asp-controller="CreatePromo" asp-action="CreateNewPromo"><i class="fa fa-rocket fa-lg" style="color:red" aria-hidden="true"></i> Create Promo</a>
                        </li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>

    @RenderBody()

    <footer>
        <section style="background-color:#dcdcdc">
            <br />
            <div class="container">
                <div class="row">
                    <div class="input-group mb-3">
                        <a class="nav-link" id="home" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        <a class="nav-link" id="features" asp-area="" asp-controller="Home" asp-action="Features">Features</a>
                        <a class="nav-link" id="pricing" asp-area="" asp-controller="Home" asp-action="Pricing">Pricing</a>
                        <a class="nav-link" id="contact" asp-area="" asp-controller="Home" asp-action="Contact">Contact Us</a>
                        @*<a class="nav-link" id="blog" asp-area="" asp-controller="Home" asp-action="Blog">Blog</a>*@
                    </div>
                </div>
                <div class="row">
                    <p>&copy; @DateTime.Now.Year - Oso Easy Promo</p>
                </div>
            </div>
        </section>

        <!--Bootstrap JS-->
        <script async src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                crossorigin="anonymous"
                integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy">
        </script>

        @RenderSection("Scripts", required: false)
        <script async src="~/js/Shared/navigation.min.js"></script>

        <environment names="Production">
            <!-- Global site tag (gtag.js) - Google Analytics -->
            <script async src="https://www.googletagmanager.com/gtag/js?id=UA-121940780-1"></script>
            <script>
                window.dataLayer = window.dataLayer || [];
                function gtag() { dataLayer.push(arguments); }
                gtag('js', new Date());
                gtag('config', 'UA-121940780-1');
            </script>
        </environment>

    </footer>
</body>
</html>